image: maven:eclipse-temurin

checkstyle:
  stage: checkstyle
  script:
    - mvn clean prettier:check

build:
  stage: build
  script:
    - mvn clean compile

test:
  stage: test
  script:
    - mvn clean test
