image: maven:latest

stages:
  - checkstyle
  - compile
  - test

checkstyle:
  stage: checkstyle
  script:
    - mvn clean prettier:check

compile:
  stage: compile
  script:
    - mvn compile
    - mvn clean

test:
  stage: test
  script:
    - mvn clean test